name: build and test app

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.20.x' # you can use 1.17
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk